import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

const Footer = () => {
  const [isDisclaimerOpen, setIsDisclaimerOpen] = useState(false);

  return (
    <footer className="bg-gray-900 text-gray-400 py-12 pb-24 sm:pb-12">
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto">
          <div className="flex flex-col md:flex-row justify-between items-center gap-6">
            {/* Company Name */}
            <div className="text-white font-semibold text-lg">
              DGTL Dental
            </div>
            
            {/* Links */}
            <div className="flex items-center gap-6 text-sm">
              <a 
                href="mailto:hello@dgtldental.com" 
                className="hover:text-white transition-colors"
              >
                hello@dgtldental.com
              </a>
              
              <Dialog open={isDisclaimerOpen} onOpenChange={setIsDisclaimerOpen}>
                <DialogTrigger asChild>
                  <button className="hover:text-white transition-colors">
                    Medical Disclaimer
                  </button>
                </DialogTrigger>
                <DialogContent className="max-w-2xl">
                  <DialogHeader>
                    <DialogTitle>Medical Disclaimer</DialogTitle>
                  </DialogHeader>
                  <div className="text-gray-600 space-y-4 text-sm leading-relaxed">
                    <p>
                      The AI dental assistant provided by DGTL Dental is designed to answer general questions about dental services, office information, and common patient inquiries. It is not intended to provide medical advice, diagnosis, or treatment recommendations.
                    </p>
                    <p>
                      All responses generated by the AI assistant are for informational purposes only and should not be considered a substitute for professional dental or medical advice. Patients should always consult with a qualified dental professional for any health-related concerns or before making decisions about their dental care.
                    </p>
                    <p>
                      The AI assistant is programmed to encourage patients to contact the dental office directly for specific medical questions, appointments, and emergencies. DGTL Dental does not assume liability for any decisions made based on information provided by the AI assistant.
                    </p>
                    <p>
                      By using this service, dental practices acknowledge that they are responsible for reviewing and ensuring the accuracy of practice-specific information provided to the AI assistant during setup.
                    </p>
                  </div>
                </DialogContent>
              </Dialog>
            </div>
          </div>
          
          {/* Copyright */}
          <div className="text-center mt-8 pt-8 border-t border-gray-800 text-sm">
            © {new Date().getFullYear()} DGTL Dental. All rights reserved.
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
