// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqshsywezmoxyzyytvnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxc2hzeXdlem1veHl6eXl0dm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTQ5NDksImV4cCI6MjA2Njg3MDk0OX0.HJlNub2omrMOiCp1MkJgc85PPcQkhrHF0It_U-RAqgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});